F1_TABLE_METADATA = """
DATABASE: f1db
"table_name","columns"
"google_columnar_engine_vectorized_join_mem_users","uncompressed_size, memory_context_name"
"poll_votes","poll_id, option_index, voted_at, user_id"
"g_columnar_agg_stat_statements","metrics"
"g_columnar_whatif_relations","size, columnar_unit_count, valid_block_count, valid_tuple_count, block_count_in_cc, num_blocks_used_for_size_estimation, num_changed_blocks_since_last_size_estimation, queued_refresh_duration_in_seconds, total_block_count, database_name, schema_name, relation_name"
"google_db_advisor_index_state","index, state"
"g_columnar_columns","size_in_bytes, last_accessed_time, num_times_accessed, database_name, schema_name, relation_name, column_name, column_type, status"
"g_columnar_indexes","size, total_node_count, non_leaf_node_count, leaf_node_count, invalid_block_count, block_count_in_cc, total_block_count, creation_time, auto_refresh_trigger_count, auto_refresh_failure_count, auto_refresh_trigger_timestamp, auto_refresh_start_timestamp, auto_refresh_end_timestamp, auto_refresh_recent_status, database_name, schema_name, index_name, status"
"user_watchlist","id, created_at, user_id, entity_type, entity_id"
"google_db_advisor_recommended_indexes_to_drop","index, last_access, storage_in_mb, benefit"
"g_columnar_index_partitions","is_leaf, start_block, end_block, invalid_block_count, total_block_count, is_primary, size, cached_size_bytes, swap_out_size_bytes, utilization, pin_count, num_datapoints, creation_time, database_name, schema_name, index_name, status, swap_status"
"f1_results","id, session_id, grid, position, classified, points, fastest_lap, driver_id, team_id, status"
"google_db_advisor_stat_statements","metric_value, metric_name, metric_type"
"g_columnar_wait_events","num_waits, elapsed_time, avg_wait, wait_name"
"g_columnar_activity","cu_start_bno, event_time, num_processes, database_name, schema_name, relation_name, column_name, event, status"
"user_tokens","expiry, updated_at, user_id, encrypted_token, scope"
"f1_drivers","number, updated_at, driver_id, code, full_name, given_name, family_name, nationality"
"polls","id, options, race_round, season, closes_at, created_at, question"
"google_db_advisor_workload_columnar_report","user_id, db_id, query_id, init_cost, new_cost, num_calls, total_time, recommended_columnar_columns"
"g_columnar_columns_internal","column_format, compression_level, avg_dictionary_count, avg_encoded_values_count, dictionary_size_in_bytes, encoded_values_size_in_bytes, size_in_bytes, uncompressed_dictionary_size_in_bytes, uncompressed_encoded_values_size_in_bytes, uncompressed_size_in_bytes, last_accessed_time, num_times_accessed, database_name, schema_name, relation_name, column_name, column_type, status"
"f1_teams","updated_at, team_id, name, nationality"
"f1_sessions","id, season, round, date, session_type, race_name, circuit_id"
"party_plans","id, guest_count, plan, created_at, user_id, race_name, theme"
"g_columnar_recommendation_stat_statements","metric_value, recommendation_algorithm, metric_name, metric_type"
"g_columnar_jobs","database_oid, relation_oid, job_id, is_schema_change_op, database_name, schema_name, relation_name, job_type, job_class, status, dependent_jobs"
"g_lap_timer","lap_time"
"google_db_advisor_workload_report_detail","report_detail"
"google_db_advisor_stats","value"
"g_columnar_stat_statements","user_id, db_id, query_id, columnar_unit_read, page_read, rows_filtered, columnar_scan_time, vectorized_join_time, vectorized_aggregation_time, vectorized_aggregation_vj_time"
"g_columnar_virtual_columns_internal","column_format, compression_level, size, size_stats, last_accessed_time, num_times_accessed, category, database_name, schemas, relations, description, column_data_type, status"
"g_columnar_units","start_block, end_block, cu_xid, invalid_block_count, columns_count, size, cached_size_bytes, swap_out_size_bytes, utilization, is_full_cu, database_name, schema_name, relation_name, type, status, swap_status, columns_swap_status"
"g_columnar_stats","count, name"
"agent_feed","id, data, race_round, season, dismissed_at, created_at, user_id, card_type, title, body"
"g_columnar_whatif_columns","compression_level, estimated_size_in_bytes, correlation, selectivity, estimated_minmax_size_in_bytes, column_name, schema_name, relation_name, database_name"
"f1_circuits","lat, lng, updated_at, circuit_id, name, locality, country"
"predictions","id, round_id, score, submitted_at, user_id, p1, p2, p3"
"google_db_advisor_workload_report","user_id, db_id, query_id, init_cost, new_cost, num_calls, total_time, recommended_indexes"
"g_columnar_virtual_columns","last_accessed_time, num_times_accessed, category, database_name, schemas, relations, description, column_data_type, status"
"google_db_advisor_workload_advisory","advisory"
"g_columnar_relations_internal","size, uncompressed_size, columnar_unit_count, invalid_block_count, block_count_in_cc, total_block_count, auto_refresh_trigger_count, auto_refresh_failure_count, auto_refresh_trigger_timestamp, auto_refresh_start_timestamp, auto_refresh_end_timestamp, auto_refresh_scan_count, database_name, schema_name, relation_name, status, auto_refresh_recent_status"
"google_db_advisor_workload_statements_with_timestamp","user_id, db_id, query_id, num_calls, total_time, last_execution_time, query"
"google_db_advisor_recommended_columnar_configuration","name, value"
"google_db_advisor_query_tuning_advices","user_id, db_id, query_id, trace_id, span_id, parent_span_id, advice"
"google_db_advisor_agg_recommendations","database_name, recommendations"
"google_db_advisor_agg_query_recommendations","database_name, recommendations"
"g_columnar_memory_usage","memory_total, memory_available, memory_available_percentage, reserved_memory, memory_name"
"prediction_rounds","id, race_round, season, closes_at, race_name"
"google_db_advisor_local_auto_config","auto_config"
"g_columnar_recommended_columns_internal","column_format, compression_level, estimated_size_in_bytes, database_name, schema_name, relation_name, column_name"
"users","id, alert_preferences, widget_settings, created_at, updated_at, name, email, fav_driver, fav_team, timezone, firebase_uid"
"google_db_advisor_catalog_auto_config","auto_config"
"g_columnar_relations","size, invalid_block_count, block_count_in_cc, total_block_count, auto_refresh_trigger_count, auto_refresh_failure_count, auto_refresh_trigger_timestamp, auto_refresh_start_timestamp, auto_refresh_end_timestamp, auto_refresh_scan_count, database_name, schema_name, relation_name, status, auto_refresh_recent_status"
"g_columnar_index_partitions_internal","start_block, end_block, invalid_block_count, total_block_count, is_leaf, is_primary, size, cached_size_bytes, swap_out_size_bytes, utilization, pin_count, num_datapoints, creation_time, swap_status, database_name, schema_name, index_name, status"
"g_columnar_native_scan_unsupported_ops","unsupported_op_name"
"user_notes","id, content, created_at, user_id, type, title"
"hypopg_list_indexes","indexrelid, index_name, schema_name, table_name, am_name"
"g_columnar_recommended_columns","estimated_size_in_bytes, database_name, schema_name, relation_name, column_name"
"f1_standings","id, season, round, position, points, wins, standing_type, entity_id"
"g_columnar_policies","policy_id, duration, next_time, database_name, schema_name, relation_name, policy_category, policy_object, policy_interval, time_unit"
"g_columnar_indexes_internal","size, total_node_count, non_leaf_node_count, leaf_node_count, invalid_block_count, block_count_in_cc, total_block_count, creation_time, auto_refresh_trigger_count, auto_refresh_failure_count, auto_refresh_trigger_timestamp, auto_refresh_start_timestamp, auto_refresh_end_timestamp, database_name, schema_name, index_name, status, auto_refresh_recent_status"
"google_db_advisor_recommended_indexes","estimated_storage_size_in_mb, num_impacted_queries, index"
"race_cache","data, cached_at, session_key"
"google_db_advisor_workload_statements","user_id, db_id, query_id, num_calls, total_time, query"
"g_agg_stat_statements","metric_value, metric_name, metric_type"
"g_columnar_column_set_stat_statements","force, benefit, relation_name, column_names, database_name, schema_name"
"user_calendar_events", "id, user_id, event_name, event_date, created_at"
"g_columnar_schedules","next_time, schedule_name, schedule"

"""