F1_TABLE_METADATA = """
DATABASE: f1db
"table_name","columns"
"f1_results","id, session_id, grid, position, classified, points, fastest_lap, driver_id, team_id, status"
"f1_drivers","number, updated_at, driver_id, code, full_name, given_name, family_name, nationality"
"f1_teams","updated_at, team_id, name, nationality"
"f1_sessions","id, season, round, date, session_type, race_name, circuit_id"
"f1_circuits","lat, lng, updated_at, circuit_id, name, locality, country"
"f1_standings","id, season, round, position, points, wins, standing_type, entity_id"
"""